import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header/header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ENEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="container w-full">
        <div>About</div>
        <div>Company（別ページ遷移予定）</div>
        <div>Works</div>
        <div>Members</div>
        <div>Contact</div>
        <div>Related Business（別ページ遷移予定）</div>
      </div>
    </div>
  )
}

export default Home
